# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jetson/image_capture_tool/image_capture_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageCaptureTool(object):
    def setupUi(self, ImageCaptureTool):
        ImageCaptureTool.setObjectName("ImageCaptureTool")
        ImageCaptureTool.resize(1280, 700)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(ImageCaptureTool)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_camera = QtWidgets.QGroupBox(ImageCaptureTool)
        self.groupBox_camera.setObjectName("groupBox_camera")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_camera)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_camera = ImageLabel(self.groupBox_camera)
        self.label_camera.setMinimumSize(QtCore.QSize(640, 480))
        self.label_camera.setObjectName("label_camera")
        self.verticalLayout.addWidget(self.label_camera)
        self.horizontalLayout_3.addWidget(self.groupBox_camera)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(ImageCaptureTool)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_tag = BodyLabel(self.groupBox)
        self.label_tag.setObjectName("label_tag")
        self.verticalLayout_2.addWidget(self.label_tag)
        self.lineEdit_tag = LineEdit(self.groupBox)
        self.lineEdit_tag.setObjectName("lineEdit_tag")
        self.verticalLayout_2.addWidget(self.lineEdit_tag)
        self.label_savedir = BodyLabel(self.groupBox)
        self.label_savedir.setObjectName("label_savedir")
        self.verticalLayout_2.addWidget(self.label_savedir)
        self.lineEdit_savedir = LineEdit(self.groupBox)
        self.lineEdit_savedir.setInputMask("")
        self.lineEdit_savedir.setDragEnabled(False)
        self.lineEdit_savedir.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_savedir.setObjectName("lineEdit_savedir")
        self.verticalLayout_2.addWidget(self.lineEdit_savedir)
        self.label_preview = BodyLabel(self.groupBox)
        self.label_preview.setObjectName("label_preview")
        self.verticalLayout_2.addWidget(self.label_preview)
        self.lineEdit_preview = LineEdit(self.groupBox)
        self.lineEdit_preview.setReadOnly(True)
        self.lineEdit_preview.setObjectName("lineEdit_preview")
        self.verticalLayout_2.addWidget(self.lineEdit_preview)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_capture = PrimaryPushButton(ImageCaptureTool)
        self.button_capture.setObjectName("button_capture")
        self.horizontalLayout.addWidget(self.button_capture)
        self.button_exit = PushButton(ImageCaptureTool)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)

        self.retranslateUi(ImageCaptureTool)
        QtCore.QMetaObject.connectSlotsByName(ImageCaptureTool)

    def retranslateUi(self, ImageCaptureTool):
        _translate = QtCore.QCoreApplication.translate
        ImageCaptureTool.setWindowTitle(_translate("ImageCaptureTool", "Image Capture Tool"))
        self.groupBox_camera.setTitle(_translate("ImageCaptureTool", "Camera"))
        self.label_camera.setText(_translate("ImageCaptureTool", "Camera"))
        self.groupBox.setTitle(_translate("ImageCaptureTool", "Options"))
        self.label_tag.setText(_translate("ImageCaptureTool", "Tag"))
        self.lineEdit_tag.setPlaceholderText(_translate("ImageCaptureTool", "e.g. battery"))
        self.label_savedir.setText(_translate("ImageCaptureTool", "Save Directory"))
        self.lineEdit_savedir.setText(_translate("ImageCaptureTool", "photos"))
        self.label_preview.setText(_translate("ImageCaptureTool", "File Name Preview"))
        self.button_capture.setText(_translate("ImageCaptureTool", "Capture (S)"))
        self.button_exit.setText(_translate("ImageCaptureTool", "Exit (Ctrl+Q)"))
from qfluentwidgets import BodyLabel, ImageLabel, LineEdit, PrimaryPushButton, PushButton
